/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EstofadosRouteImport } from './routes/estofados'
import { Route as IndexRouteImport } from './routes/index'

const EstofadosRoute = EstofadosRouteImport.update({
  id: '/estofados',
  path: '/estofados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estofados': typeof EstofadosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estofados': typeof EstofadosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estofados': typeof EstofadosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/estofados'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/estofados'
  id: '__root__' | '/' | '/estofados'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstofadosRoute: typeof EstofadosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/estofados': {
      id: '/estofados'
      path: '/estofados'
      fullPath: '/estofados'
      preLoaderRoute: typeof EstofadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstofadosRoute: EstofadosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
